
package numerospseudoaleatorios;

import javax.swing.table.DefaultTableModel;

/************************************************************
 *                 Universidad del Valle                    *
 *                                                          *
 *                Numeros pseudoaleatorios                  *
 *                      CHI CUADRADO                        *
 *                                                          *
 *                                                          *   
 *        Estudiantes                       Codigos         *
 * Luz Carime Lucumi Hernandez              1667564         *
 * Stiven Pinzón Triana                     1667614         *
 *                                                          *
 ************************************************************/

/**
 *
 * @author Luz Carime Lucumi®
 * @author Stiven® * 
 */
public class ChiCuadrado extends javax.swing.JFrame {
    /**
     * Creates new form ChiCuadrado
     */
    DefaultTableModel modelo;
    
    public ChiCuadrado(double[][] tabla, double cantidad) {
        
        initComponents();
        
        String cabecera[]={"Rango Inferior", "Rango superior","FO","FE","(FE-FO)²/FE"};
        String datos[][]={};
        
        
        modelo= new DefaultTableModel(datos, cabecera);
        tblChi.setModel(modelo);
        
        double intervalo= 0,contador=0,FO,FE,Chi;
        //Se llena la tabla tblChi
        for (int i = 0; i < 11; i++) {
            //Se muestran en la tabla los valores de cada cálculo según corresponda
            if(i<10){
                //Obtenemos el valor de FO de la clase PruebaDeBondad
                FO=tabla[i][0];
                FE=cantidad/10;
                Chi=Math.pow((FO-FE),2)/FE;
                //contador, lleva la suma de los valores de la última columna
                contador+=Chi;
                //Se agregan tanto intérvalos como valores calculados a cada fila
                Object datos2[]={String.format("%.1f", intervalo),String.format("%.1f", intervalo+0.1),FO,FE,Chi};
                //se aumenta en 0.1 el intervalo siguiente
                intervalo=intervalo+0.1;
                modelo.addRow(datos2);
                tblChi.setModel(modelo);
            }
            else{
                //Se muestra en la tabla el valor correspondiente a la suma de los valores
                //de la última columna
                Object datos2[]={"","","","Σ(FE-FO)²/FE",contador};
                modelo.addRow(datos2);
                tblChi.setModel(modelo);
                //Se valida si cumple o no con las condiciones para la hipótesis
                //referente a datos con la distribucion U(0,1)
                if(contador<=16.92){
                    labelCumple2.setVisible(true);
                    labelCumple3.setVisible(true);
                    labelCumple.setVisible(false);
                    labelCumple1.setVisible(false);
                }
                else{
                    labelCumple.setVisible(true);
                    labelCumple1.setVisible(true);
                    labelCumple2.setVisible(false);
                    labelCumple3.setVisible(false);
                }
            }
        }
    }

    private ChiCuadrado() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label6 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChi = new javax.swing.JTable();
        label4 = new java.awt.Label();
        label3 = new java.awt.Label();
        label5 = new java.awt.Label();
        labelCumple = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        labelCumple1 = new java.awt.Label();
        label11 = new java.awt.Label();
        labelCumple2 = new java.awt.Label();
        labelCumple3 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        label1.setText("label1");

        label2.setText("label2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChi.setEnabled(false);
        jScrollPane2.setViewportView(tblChi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 550, 210));

        label4.setBackground(new java.awt.Color(255, 255, 255));
        label4.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        label4.setText("PRUEBA X²");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label3.setText("Grados de libertad (gl)");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, 20));
        label3.getAccessibleContext().setAccessibleDescription("");

        label5.setBackground(new java.awt.Color(255, 255, 255));
        label5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label5.setText("9");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        labelCumple.setBackground(new java.awt.Color(255, 255, 255));
        labelCumple.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        labelCumple.setText("X² calc >  X² crit");
        labelCumple.setVisible(false);
        getContentPane().add(labelCumple, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 150, -1));
        labelCumple.getAccessibleContext().setAccessibleName("");

        label7.setBackground(new java.awt.Color(255, 255, 255));
        label7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label7.setText("16,92");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        label8.setBackground(new java.awt.Color(255, 255, 255));
        label8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(51, 51, 51));
        label8.setText("Nivel de confianza (a) ");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        label9.setBackground(new java.awt.Color(255, 255, 255));
        label9.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label9.setText("0,05");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        labelCumple1.setBackground(new java.awt.Color(255, 255, 255));
        labelCumple1.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        labelCumple1.setText("No se acepta la hipótesis de que los datos tienen distribución U(0,1)");
        labelCumple1.setVisible(false);
        getContentPane().add(labelCumple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 420, -1));
        labelCumple1.getAccessibleContext().setAccessibleName("");

        label11.setBackground(new java.awt.Color(255, 255, 255));
        label11.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label11.setText("X² crit ");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 60, 20));

        labelCumple2.setBackground(new java.awt.Color(255, 255, 255));
        labelCumple2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        labelCumple2.setText("X² calc <=  X² crit");
        labelCumple2.setVisible(false);
        getContentPane().add(labelCumple2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 160, -1));

        labelCumple3.setBackground(new java.awt.Color(255, 255, 255));
        labelCumple3.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        labelCumple3.setText("Se acepta la hipótesis de que los datos tienen distribución U(0,1)");
        labelCumple3.setVisible(false);
        getContentPane().add(labelCumple3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 400, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChiCuadrado.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiCuadrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    public static java.awt.Label labelCumple;
    public static java.awt.Label labelCumple1;
    public static java.awt.Label labelCumple2;
    public static java.awt.Label labelCumple3;
    public static javax.swing.JTable tblChi;
    // End of variables declaration//GEN-END:variables
}
