/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numerospseudoaleatorios;

/**
 *
 * @author miime_000
 */
public class Corridas extends javax.swing.JFrame {

    /**
     * Creates new form Corridas
     */
    public Corridas(String signo, int cantidad,double mediaC, double varianzaC, double zC) {
        initComponents();
        totalcorridas.setText(""+cantidad);
        media.setText(""+ mediaC);
        varianza.setText(""+ varianzaC);
        z.setText(""+ zC);
        jTextAreaCorrida.append(signo);
    }

    private Corridas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCorrida = new javax.swing.JTextArea();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        totalcorridas = new java.awt.Label();
        z = new java.awt.Label();
        label8 = new java.awt.Label();
        varianza = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        media = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaCorrida.setColumns(20);
        jTextAreaCorrida.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCorrida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 440, 200));

        label1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        label1.setText("CORRIDAS");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 140, 28));

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Comportamiento de crecimiento-decrecimiento");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 420, -1));

        label3.setEnabled(false);
        label3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label3.setText("Zabs");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        totalcorridas.setEnabled(false);
        totalcorridas.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        getContentPane().add(totalcorridas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 40, -1));

        z.setEnabled(false);
        z.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        getContentPane().add(z, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 60, -1));

        label8.setEnabled(false);
        label8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(51, 51, 51));
        label8.setText("Media");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        varianza.setEnabled(false);
        varianza.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        getContentPane().add(varianza, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 70, -1));

        label11.setEnabled(false);
        label11.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label11.setText("Cantidad corridas");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        label12.setEnabled(false);
        label12.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label12.setText("Varianza");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        media.setEnabled(false);
        media.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        getContentPane().add(media, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Corridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Corridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Corridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Corridas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Corridas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCorrida;
    private java.awt.Label label1;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label8;
    private java.awt.Label media;
    private java.awt.Label totalcorridas;
    private java.awt.Label varianza;
    private java.awt.Label z;
    // End of variables declaration//GEN-END:variables
}
