/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numerospseudoaleatorios;

/**
 *
 * @author miime_000
 */
public class Generadores extends javax.swing.JFrame {

    /**
     * Creates new form Corrida
     */
    public Generadores(String valor, boolean elegido) {
        initComponents();
        //Se muestran los datos generados según el 
        //generador que 'elegido' indique
        TextAreaCorridas.append(valor);
        
        //Si elegido es verdadero se imprimen los label de Lineal Congruente
        if(elegido){
            labelEM.setVisible(false);
            labelLC.setVisible(true);
        }
        //en caso contrario se mostrarán los de Estandar Minimo
        else{
            labelLC.setVisible(false);
            labelEM.setVisible(true);
        }
    }

    private Generadores() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextAreaCorridas = new java.awt.TextArea();
        labelLC = new java.awt.Label();
        label2 = new java.awt.Label();
        labelEM = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 455));
        getContentPane().setLayout(null);
        getContentPane().add(TextAreaCorridas);
        TextAreaCorridas.setBounds(20, 120, 509, 228);

        labelLC.setBackground(new java.awt.Color(255, 255, 255));
        labelLC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelLC.setText("LINEAL CONGRUENTE");
        labelLC.setVisible(false);
        getContentPane().add(labelLC);
        labelLC.setBounds(320, 90, 210, 28);

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("GENERADOR NUMEROS PSEUDOALEATORIOS ");
        getContentPane().add(label2);
        label2.setBounds(80, 30, 420, 28);

        labelEM.setBackground(new java.awt.Color(255, 255, 255));
        labelEM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEM.setText("ESTANDAR MINIMO");
        labelEM.setVisible(false);
        getContentPane().add(labelEM);
        labelEM.setBounds(350, 90, 180, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChiCuadrado.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea TextAreaCorridas;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label2;
    private java.awt.Label labelEM;
    private java.awt.Label labelLC;
    // End of variables declaration//GEN-END:variables
}
