
package numerospseudoaleatorios;

import javax.swing.table.DefaultTableModel;

/************************************************************
 *                 Universidad del Valle                    *
 *                                                          *
 *                Numeros pseudoaleatorios                  *
 *                    SERIES: TABLA 2                       *
 *                                                          *
 *                                                          *   
 *        Estudiantes                       Codigos         *
 * Luz Carime Lucumi Hernandez              1667564         *
 * Stiven Pinzón Triana                     1667614         *
 *                                                          *
 ************************************************************/

/**
 *
 * @author Luz Carime Lucumi®
 * @author Stiven®
 */
public class SeriesTabla2 extends javax.swing.JFrame {
    DefaultTableModel modelo;
    /**
     * Creates new form Series
     * @param tabla2
     * @param cantidad
     */
    public SeriesTabla2(double[][]tabla2, int cantidad) {
        initComponents();
        String cabecera[]={"","0-0.2","0.2-0.4","0.4-0.6","0.6-0.8","0.8-1"};
        String datos[][]={};
        
        
        modelo= new DefaultTableModel(datos, cabecera);
        tblSeries1.setModel(modelo);
        double intervalo=0,intervalof=0.2;
        String dato1="",dato2="";
        
        //Se llena la tabla tblChi
        for (int i = 0; i < 5; i++) {
            dato1=String.format("%.1f", intervalo);
            dato2=String.format("%.1f", intervalof);
            Object datos2[]={dato1+" - "+dato2,tabla2[i][0],tabla2[i][1],tabla2[i][2],tabla2[i][3],tabla2[i][4]};
            intervalo+=0.2;
            intervalof+=0.2;
            modelo.addRow(datos2);
            tblSeries1.setModel(modelo);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblSeries1 = new javax.swing.JTable();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(513, 449));
        setResizable(false);
        getContentPane().setLayout(null);

        tblSeries1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSeries1.setEnabled(false);
        jScrollPane3.setViewportView(tblSeries1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(60, 160, 380, 110);

        label5.setBackground(new java.awt.Color(240, 240, 240));
        label5.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        label5.setText("SERIES");
        getContentPane().add(label5);
        label5.setBounds(90, 110, 80, 30);

        label6.setBackground(new java.awt.Color(255, 255, 255));
        label6.setFont(new java.awt.Font("Euphemia", 1, 18)); // NOI18N
        label6.setText("Tabla 2");
        getContentPane().add(label6);
        label6.setBounds(310, 280, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChiCuadrado.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 840, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeriesTabla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeriesTabla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeriesTabla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeriesTabla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeriesTabla2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label5;
    private java.awt.Label label6;
    public static javax.swing.JTable tblSeries1;
    // End of variables declaration//GEN-END:variables

    private SeriesTabla2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
